import type { NextPage } from 'next';
import type { AppProps, AppContext } from 'next/app';
import App from 'next/app';
import Head from 'next/head';
import Header from '../../src/components/Header';
import styles from '../../styles/Home.module.css';
import { PROJECTS_ENDPOINT, PROJECTS_ORIGIN } from '../../src/helpers/constants';

const Projects: NextPage = ({ projectData }: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header title="Projects" />

      <main className={styles.main}>

        <div className={styles.grid}>
          {projectData?.length ?
            (<ul>
              {projectData.map((item: String, index: Number) => {
                return <li><a href={`/projects/${item}`}>{item}</a></li>
              })}
            </ul>)
            :
            <div>Loading...</div>}
        </div>
      </main>

      <footer className={styles.footer}>
        Homemade by Roland Levy
      </footer>
    </div>
  )
}

Projects.getInitialProps = async () => {
  const response = await fetch(`${PROJECTS_ENDPOINT}/project-categories?origin=${PROJECTS_ORIGIN}`);
  const data = await response.json();
  return {
    projectData: data
  };
}

export default Projects;
