import { useEffect, useContext } from 'react';
import type { NextPage } from 'next';
import { useRouter } from 'next/router';
import Link from 'next/link';
import Head from 'next/head';
import styles from '../../../styles/Home.module.css';
import { getSectionData } from '../../../src/helpers/utils';
import Header from '../../../src/components/Header';
import { PROJECTS_ENDPOINT, PROJECTS_ORIGIN } from '../../../utils/constants';

const Category: NextPage = ({ categoryData }: any) => {
  const router = useRouter();
  const { category } = router.query;
  return (
    <div className={styles.container}>
      <Head>
        <title>{category}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header page={category} />

      <main className={styles.main}>

        <div className={styles.grid}>
          {categoryData?.length ? (
            <ul className={styles.card}>
              {categoryData.map((item:any) => (
                <li>
                  <Link 
                    href="/projects/[category]/[${item.id}]"
                    as={`/projects/${category}/${item.id}`}
                  >    
                    <a>{item.heading}</a>
                  </Link>  
                </li>
              ))}
            </ul>
            ) : <div>Loading...</div>}
        </div>
      </main>

      <footer className={styles.footer}>
        Homemade by Roland Levy
      </footer>
    </div>
  )
}

Category.getInitialProps = async (context) => {
  const { req, res, query } = context;
  const { category } = query;
  const response = await fetch(`${PROJECTS_ENDPOINT}/project-category/${category}?origin=${PROJECTS_ORIGIN}`);
  const categoryData = await response.json();
  return {
    categoryData
  };
}

// export const getServerSideProps = async () => {
//   try {
//     console.log('CONNECTING TO MONGO');
//     await connectMongo();
//     console.log('CONNECTED TO MONGO');

//     console.log('FETCHING DOCUMENTS');
//     const tests = await Test.find();
//     console.log('FETCHED DOCUMENTS');

//     return {
//       props: {
//         tests: JSON.parse(JSON.stringify(tests)),
//       },
//     };
//   } catch (error) {
//     console.log(error);
//     return {
//       notFound: true,
//     };
//   }
// };

export default Category;
