import { useEffect, useContext } from 'react';
import type { NextPage } from 'next';
import { useRouter } from 'next/router';
import Link from 'next/link';
import Head from 'next/head';
import styles from '../../../styles/Home.module.css';
import { getSectionData } from '../../../src/helpers/utils';
import Header from '../../../src/components/Header';
import { PROJECTS_ENDPOINT, PROJECTS_ORIGIN } from '../../../utils/constants';

const Category: NextPage = ({ categoryData }: any) => {
  const router = useRouter();
  const { category } = router.query;
  return (
    <div className={styles.container}>
      <Head>
        <title>{category}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header page={category} />

      <main className={styles.main}>

        <div className={styles.grid}>
          {categoryData?.length ? (
            <ul className={styles.card}>
              {categoryData.map((item:any) => (
                <li>
                  <Link 
                    href="/projects/[category]/[${item.id}]"
                    as={`/projects/${category}/${item.id}`}
                  >    
                    <a>{item.heading}</a>
                  </Link>  
                </li>
              ))}
            </ul>
            ) : <div>Loading...</div>}
        </div>
      </main>

      <footer className={styles.footer}>
        Homemade by Roland Levy
      </footer>
    </div>
  )
}

Category.getInitialProps = async (context) => {
  try {
    const { req, res, query, asPath, pathname } = context;
    const { category } = query;
    const { host }:any = req?.headers;
    const url = `https://${host}/api/project-category/${category}`;
    const response = await fetch(url);
    const categoryData = await response.json();
    return {
      categoryData
    };
  } catch (error) {
    console.log(error);
    return {
      notFound: true,
    };
  }
}

export default Category;
