import type { NextPage } from 'next';
import Head from 'next/head';
import Header from '../src/components/Header';
import styles from '../styles/Home.module.css';

const About: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header title="About" />

      <main className={styles.main}>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Background</h2>
            <p>a full-stack developer, specialising in front-end</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Tech skills</h2>
            <p>JavaScript, React, Node, Express and other languages</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>CV</h2>
            <p>LinkedIn link, Download button</p>
          </a>

          <a
            href="https://docs.replit.com/category/hosting"
            className={styles.card}
          >
            <h2>Github</h2>
            <p>
              Github account link
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        Homemade by Roland Levy
      </footer>
    </div>
  )
}

export default About;
